#!/bin/sh -e

function usage {
    echo "Usage: $0"
    exit 1
}

function get_version {
   version= ./updatectl --version | cut -d " " -f 3
   return $version
}

version=v`get_version`
git tag $version
